# Generated by Django 4.2.15 on 2025-07-02 21:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTag',
            fields=[
                ('tagId', models.AutoField(primary_key=True, serialize=False)),
                ('organizationName', models.CharField()),
                ('tagName', models.CharField(default='core', unique=True)),
                ('expirationDate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(default='0000000000')),
                ('role', models.CharField(default='user')),
                ('Password', models.CharField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('blockedTimestamp', models.DateField(default=datetime.date.today)),
                ('created_date', models.DateField()),
                ('blocked', models.BooleanField()),
                ('tag', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organizationtag')),
            ],
        ),
    ]
