# Generated by Django 4.2.15 on 2025-07-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Password',
            new_name='encryptedPassword',
        ),
    ]
