# Generated by Django 4.2.15 on 2025-07-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_password_userdetails_encryptedpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='created_date',
        ),
    ]
