# Generated by Django 4.2.15 on 2025-07-04 03:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_userdetails_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organizationtag'),
        ),
    ]
